name: auto_update_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_autoupdate: ^1.0.0
  permission_handler: ^8.1.4+2

dev_dependencies:
  change_app_package_name: ^1.0.0 # flutter pub run change_app_package_name:main dev.soluciones.auto_update_test
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
